worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 100m;
	
    client_header_timeout 120s;
    client_body_timeout 120s;
    
    proxy_read_timeout 120s;
    server {
        listen       9000;
        server_name  localhost;
        charset utf-8;
		server_tokens off;

		error_page 405 =200  $request_uri;
		
		location /xian {
			alias   html/dist/;
			index   index.html index.htm;
			autoindex off;
			try_files $uri $uri/ /xian/index.html;
		}

		location /xian-app/ {
            alias html/mobile/;
			autoindex off;
            try_files $uri $uri/ /index.html last;
            index  index.html;
        }  
		
        location /xian-admin/{
		    proxy_read_timeout 120s;
			proxy_connect_timeout 120s;
			proxy_send_timeout 120s;
			proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_pass http://10.200.128.43:9090/xian-admin/;
        }
		
		location /lowcode-server/ {
			proxy_pass http://10.200.128.43:8888/lowcode-server/;
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
		
		
		
		location /mes/ {
			proxy_pass http://10.200.128.46:9009/mes/;
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}
		location /mi/ {
			proxy_pass http://10.200.128.43:9010/mi/;
			proxy_set_header Host $http_host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header REMOTE-HOST $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
		}

		
		
		
        error_page   500 502 503 504   /50x.html;

        location = /50x.html {
            root   html;
        }
			
    }
	
}